"""empty message

Revision ID: c47e011fa03c
Revises: 0da578d03634
Create Date: 2024-01-02 23:53:39.132915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47e011fa03c'
down_revision = '0da578d03634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            existing_type=sa.VARCHAR(length=256),
            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            existing_type=sa.VARCHAR(length=256),
            nullable=True)

    # ### end Alembic commands ###
